### ISSUE TITLE
Plugin not working on new version of sketch (50)

### ISSUE THREAD

**Issue by PrinceSyed** [sureskumar/sketch-isometric#27] opened 2018-05-12 04:42 UTC

**Comment by gokul0** [comment] 2018-05-12 05:31
The issue is referred in  #25 and will be closed when it is fixed.

**Comment by sureskumar** [comment] 2018-05-12 05:49
The bug is now fixed in the latest version. Sorry for the inconvenience!

**Closed by sureskumar** 2018-05-12 05:49 UTC
